package meeting.system.meetings.core.dto;

public enum ScheduleMeetingFailure {
    MEETING_DATE_IS_NOT_3_DAYS_IN_ADVANCE,
    USER_IS_NEITHER_GROUP_ORGANIZER_OR_GROUP_MEMBER,
    MEETING_GROUP_DOES_NOT_EXIST,
    MEETING_NAME_IS_BLANK,
    MEETING_NAME_IS_NOT_UNIQUE,
    FEE_CANNOT_BE_LOWER_THAN_ONE,
    ATTENDEES_LIMIT_CANNOT_BE_LESS_THAN_ONE
}